### ISSUE TITLE
Running tests on Firefox (Mac and Windows) consistently doesn't return results

### ISSUE THREAD

**Issue by daveashworth** [philipwalton/easy-sauce#3]
I've noticed that when running tests using Firefox on both Mac (10.11) and Windows (10), the test results never return. Firefox on Linux doesn't have this issue.

I can open the dashboard and watch live the tests executing and passing for Mac and Windows, but the session continues on for almost 7 minutes with no results reported. Eventually, the session disconnects and reports that there were test failures.

Browser Config:

```
[ [ "Windows 10", "firefox", "latest" ],
  [ "Mac 10.11", "firefox", "latest" ],
  [ "Linux", "firefox", "latest" ]
]
```

Console report:
<img width="509" alt="screen shot 2016-07-14 at 2 29 50 pm" src="https://cloud.githubusercontent.com/assets/1932814/16852872/88370c2e-49cf-11e6-99db-1deae9ca9f85.png">

Saucelabs Dashboard (Linux session success, the other two still waiting):
<img width="777" alt="screen shot 2016-07-14 at 2 31 12 pm" src="https://cloud.githubusercontent.com/assets/1932814/16852914/b5223e52-49cf-11e6-9127-f199b4f11999.png">

Live screenshot from the open test  window:
<img width="723" alt="screen shot 2016-07-14 at 2 31 28 pm" src="https://cloud.githubusercontent.com/assets/1932814/16852932/c71fdcf4-49cf-11e6-9080-e4c8b0a980fa.png">

Not sure what other information may be helpful here, but glad to provide more if needed. Have you experienced the same?

**Comment by daveashworth** [comment]
Also, after calling out a few earlier versions of Firefox on Mac/Windows, it seems like the reporting issue only happens on version 47. 45 & 46 seem to work fine as well, but 47 never returns.

**Comment by philipwalton** [comment]
When a test hangs like that, it usually means Sauce Labs isn't able to access the test results on the `window.mochaResults` property.

Have you looked at the developer console to see if any errors are being thrown? Try to open the test page up in FF while the tests are running to see what value `window.mochaResults` returns.

**Comment by daveashworth** [comment]
It looks like `window.mochaResults` contains the correct results. There are no errors, just a few warnings.

![mocharesults](https://cloud.githubusercontent.com/assets/1932814/16861672/95cf0a24-4a08-11e6-891c-21fde374ec36.gif)

Maybe it's a saucelabs issue?

**Comment by philipwalton** [comment]
It might be. I've had random failures before. Is it consistently the same browsers that fail? What if you run them individually?

Another thing you could try is opening up `easy-sauce` in your `node_modules` folder and putting `console.log(JSON.stringify(body, null, 2))` in the following lines:
- https://github.com/philipwalton/easy-sauce/blob/0.3.5/lib/easy-sauce.js#L118
- https://github.com/philipwalton/easy-sauce/blob/0.3.5/lib/easy-sauce.js#L150

That will print out whatever the API response is from Sauce Labs, and may help you debug.

**Comment by daveashworth** [comment]
It's consistently Firefox 47 (latest) on Mac 10.11 and Windows 10. It doesn't seem to matter whether I run it in a group of other browsers, or whether it runs alone, I've _never_ seen this browser complete the tests. The `console.log` statement returns this over and over, even though in the browser, the results show as completed:

```
{
  "completed": false,
  "js tests": [
    {
      "url": "https://saucelabs.com/jobs/35f5fff357634b1480335fe4e8eedf98",
      "platform": [
        "Mac 10.11",
        "firefox",
        "latest"
      ],
      "status": "test session in progress",
      "id": "89b3cf69bcae44ad85358be41c3a1058",
      "job_id": "35f5fff357634b1480335fe4e8eedf98"
    }
  ]
}
```

Pretty strange.

**Comment by daveashworth** [comment]
Oh! That url has some useful info. This is _also_ shown over and over in the dashboard:

<img width="532" alt="screen shot 2016-07-14 at 10 39 27 pm" src="https://cloud.githubusercontent.com/assets/1932814/16862967/f0671412-4a13-11e6-8a3b-6c001dbad4a6.png">

I also found this related to the error about permission denied:

> https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

Could that have something to do with it? Seems like more people would be experiencing this issue with saucelabs and firefox if so...

**Comment by daveashworth** [comment]
It looks like there was an outstanding bug on Firefox 47.0 with selenium webdriver. Saucelabs is applying the upgrade to 47.0.1 across their cloud and I'll see if that fixes the issue. Thanks for your help again.

**Comment by philipwalton** [comment]
Ahh, yes, I forgot I had a similar issue with FF 47 a few weeks ago. I even made a comment out it in my source code!
https://github.com/googleanalytics/autotrack/blob/1.0-dev/wdio.conf.js#L223

Hard to say for sure, but this might have had something to do with FF changing their default webdriver client to [Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver) in version 47. I know that cause me problems when trying to run webdriver locally.
