### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by DylanPiercey** [philipwalton/easy-sauce#9]
Is there a way to configure how many tests can run at a time with this plugin? How would you go about doing that?

**Comment by philipwalton** [comment]
I don't think this is even supported by Sauce Labs' uniting feature:
https://wiki.saucelabs.com/display/DOCS/JavaScript+Unit+Testing+Methods

From what I can tell, Sauce Labs automatically manages queuing these for you in cases where you specify more platforms than your testing plan allows.

**Comment by DylanPiercey** [comment]
@philipwalton thanks for the info. I am hitting ngroks rate limits (not saucelabs) so understandable that they do not have an api for it.

**Comment by philipwalton** [comment]
Yeah, I was hitting those as well, which is why we added support for localtunnel and sauce connect.
